import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/custom/shared/footer";
import { ModeToggle } from "@/components/custom/navbar/mode-toggle";
import Navbar from "@/components/custom/navbar/nav-bar";
import NumResult from "@/components/custom/navbar/num-results";
import Search from "@/components/custom/navbar/search";
import Logo from "@/components/custom/navbar/logo";
import ReactQueryProvider from "./ReactQueryProvider";
export const metadata: Metadata = {
  title: "Movie Masala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto max-w-screen-xl">
            <Navbar className="sticky top-0 z-50 mx-0 gap-4 lg:mx-7 lg:mt-4 2xl:mx-0">
              <Logo />
              <Search />
              <NumResult />
              <ModeToggle />
            </Navbar>
            <section className="px-6 2xl:px-0">
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </section>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
