import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/custom/shared/footer";
import { ModeToggle } from "@/components/custom/navbar/mode-toggle";
import Navbar from "@/components/custom/navbar/nav-bar";
import NumResult from "@/components/custom/navbar/num-results";
import Search from "@/components/custom/navbar/search";
export const metadata: Metadata = {
  title: "Movie Masala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="max-w-screen-xl mx-auto">
            <Navbar className="lg:mt-4 sticky top-0 gap-4 z-50 mx-0 lg:mx-7 2xl:mx-0">
              <span className="font-semibold hidden md:block text-lg">🎬 Movie-Masala</span>
              <Search />
              <NumResult />
              <ModeToggle />
            </Navbar>
            <section className="px-6 2xl:px-0">{children}</section>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
